# Generated by Django 5.2.11 on 2026-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_reservationmodel_reservationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'APPROVED'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('Book', 'Book'), ('Pending', 'Pending'), ('Booked', 'Booked'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
